server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties],optional:file:./ticketing-system/.env[.properties],optional:file:./ticketing-system/src/main/resources/.env[.properties]
  application:
    name: ticketing-system
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketing_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}

jwt:
  secret: ${JWT_SECRET:9zFz4xk8K2hQvJrP1wM7yE6uC3bTn5L0sDqA8fGvRjXcH9pW2mN4ZtYB6eUoI1KqQh7rXvL2aF5mP8sD3cG0Jw==}
  expiration: ${JWT_EXPIRATION:86400000}

auth:
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:604800000}

scheduler:
  reservation:
    fixed-delay: ${RESERVATION_SCHEDULER_DELAY:60000}
    expiry-time-ms: ${RESERVATION_EXPIRY_TIME_MS:900000}
    batch-size: ${RESERVATION_EXPIRY_BATCH_SIZE:50}
  notification:
    fixed-delay: ${NOTIFICATION_RETRY_DELAY:120000}
    max-retry: ${NOTIFICATION_MAX_RETRY:3}
    batch-size: ${NOTIFICATION_RETRY_BATCH_SIZE:20}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

