server:
  port: 8080

spring:
  application:
    name: ticketing-system

datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "this-jwt-secret-wriiten-by-me-ashish-eykasjkjsjaiqwqookmmaskmaslmljj@jsaksajsajj-end"
  expiration: 86400000
